plugins {
    id 'java'
    id 'war'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    // Jakarta EE 10 API (provided, т.к. Tomcat его содержит)
    providedCompile 'jakarta.platform:jakarta.jakartaee-api:8.0.0'

    // JSTL для работы с тегами <c:forEach>, <c:if> и др.
    implementation 'javax.servlet:jstl:1.2'
}




war {
    archiveFileName = "laba-hayp.war"
}

test {
    useJUnitPlatform()
}
