input {
  file {
    path => "/usr/share/logstash/logs/app.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"  # вместо NUL для Linux (Docker контейнер)
    codec => multiline {
      pattern => "^\?\?\?"
      negate => true
      what => "previous"
    }
  }
}

filter {
  grok {
    match => { "message" => "INFO: result: %{GREEDYDATA:json_data}" }
    remove_field => ["message"]
  }

  json {
    source => "json_data"
    target => "parsed"
    remove_field => ["json_data"]
  }

  date {
    match => ["[parsed][time]", "ISO8601"]
    target => "@timestamp"
    remove_field => ["[parsed][time]"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "app-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
