input {
  beats {
    port => 5044
  }
}

filter {
  grok {
    match => { "message" => "INFO: result: %{GREEDYDATA:json_data}" }
    tag_on_failure => ["grok_failed"]
  }

  if "_grokparsefailure" not in [tags] {
    json {
      source => "json_data"
      tag_on_failure => ["json_failed"]
    }

    if [x] and [y] {
      date {
        match => ["time", "ISO8601"]
        target => "@timestamp"
        timezone => "Europe/Moscow"
        remove_field => ["time"]
      }

      mutate {
        convert => { "execTime" => "integer" }
        convert => { "x" => "float" }
        convert => { "y" => "float" }
        convert => { "r" => "float" }
      }

      prune {
        whitelist_names => ["x", "y", "r", "execTime", "hit", "@timestamp"]
      }
    } else {
      drop { }
    }
  } else {
    drop { }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "app-logs"
  }

  stdout {
    codec => rubydebug
  }
}
